# .github/workflows/ci.yml
name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v3
    - name: Проверка Dockerfile
      run: |
        echo "Содержимое Dockerfile:"
        cat Dockerfile
    - name: Сборка Docker-образа
      run: docker build -t my-mini-project .
